version: '3'
services:
  web:
    build:
      context: ./
    ports:
      - "80:${PORT}"
    env_file: .env
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=config.ProductionConfig
