"""empty message

Revision ID: 147493581a38
Revises: 3a57cc4b85d3
Create Date: 2022-03-25 21:26:43.669836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147493581a38'
down_revision = '3a57cc4b85d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('data', sa.String(), nullable=True))
    op.drop_constraint(None, 'inbox', type_='foreignkey')
    op.drop_constraint(None, 'inbox', type_='foreignkey')
    op.drop_constraint(None, 'inbox', type_='foreignkey')
    op.drop_column('inbox', 'like')
    op.drop_column('inbox', 'follow')
    op.drop_column('inbox', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('post', sa.VARCHAR(), nullable=True))
    op.add_column('inbox', sa.Column('follow', sa.VARCHAR(), nullable=True))
    op.add_column('inbox', sa.Column('like', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'inbox', 'post', ['post'], ['id'])
    op.create_foreign_key(None, 'inbox', 'like', ['like'], ['id'])
    op.create_foreign_key(None, 'inbox', 'requests', ['follow'], ['id'])
    op.drop_column('inbox', 'data')
    # ### end Alembic commands ###
