"""empty message

Revision ID: 3a57cc4b85d3
Revises: 6c1ec4f10b2b
Create Date: 2022-03-23 03:53:26.597593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a57cc4b85d3'
down_revision = '6c1ec4f10b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remote_node',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remote_node')
    # ### end Alembic commands ###
