"""empty message

Revision ID: 9e1181061137
Revises: 6c1ec4f10b2b
Create Date: 2022-03-22 19:35:07.966292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1181061137'
down_revision = '6c1ec4f10b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('displayName', sa.String(), nullable=True),
    sa.Column('githubId', sa.String(), nullable=True),
    sa.Column('profileImageId', sa.String(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('isVerified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remote_node',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('unlisted', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('contentType', sa.Enum('markdown', 'plain', 'png', 'jpg', name='contenttype'), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('initiated', sa.String(), nullable=True),
    sa.Column('to', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['initiated'], ['author.id'], ),
    sa.ForeignKeyConstraint(['to'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('contentType', sa.Enum('markdown', 'plain', 'png', 'jpg', name='contenttype'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['author.id'], ),
    sa.ForeignKeyConstraint(['post'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viewablePostRelation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('viewConsumer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['post'], ['post.id'], ),
    sa.ForeignKeyConstraint(['viewConsumer'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['author.id'], ),
    sa.ForeignKeyConstraint(['comment'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['post'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbox',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('like', sa.String(), nullable=True),
    sa.Column('follow', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['follow'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['like'], ['like.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['author.id'], ),
    sa.ForeignKeyConstraint(['post'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inbox')
    op.drop_table('like')
    op.drop_table('viewablePostRelation')
    op.drop_table('comment')
    op.drop_table('requests')
    op.drop_table('post')
    op.drop_table('remote_node')
    op.drop_table('author')
    # ### end Alembic commands ###
