"""empty message

Revision ID: a9a1dbe52778
Revises: c4d94bdc13f8
Create Date: 2022-04-03 21:00:20.368823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a1dbe52778'
down_revision = 'c4d94bdc13f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('source', sa.String(), nullable=True))
    op.add_column('post', sa.Column('origin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'origin')
    op.drop_column('post', 'source')
    # ### end Alembic commands ###
