name: unit tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  python:
    runs-on: ubuntu-latest
    working-directory: server

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'

      - name: virtual environment
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: pytest
        run: |
          DATABASE_URL=sqlite:///test.db flask db upgrade
          pytest --cov=. tests.py

  # javascript:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'

  #     - run: npm ci

  #     - name: jest
  #       run: npm test
